extends: 
  - airbnb-base
  - plugin:node/recommended
env:
  node: true
  mocha: true
  es2022: true
plugins:
  - import
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  no-console: 0
  # Sometimes I like a single 'return' statement in a full bloc, e.g. see the
  # tests, so relax the requirement to have single return statements
  arrow-body-style: 0
  import/no-extraneous-dependencies: [error, { devDependencies: ['**/*.specs.js'] }]
  no-process-exit: 0
  node/no-unpublished-require: 0
  node/no-missing-require: 0
  # Allow both LF and CRLF line endings for cross-platform compatibility
  linebreak-style: 0
  # Disable shebang line ending enforcement for cross-platform compatibility
  node/shebang: 0
